---
# This playbook will install mysql and create db user and give permissions.

- name:  Install MariaDB server package  # cambié el servicio de mysql a Mariadb ya que presentaba paquetes incompletos
  apt: name=mariadb-server state=present

- name:  Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package
  apt: name=python-mysqldb state=present

- name: Install mysql extension for php
  apt: name = {{item}} state:present
  with_items:
    - php5-mysql

- name:  Create a new database
  mysql_db: name={{nomdb}} state=present collation=utf8_general_ci

- name:  Create a database user
  mysql_user: name={{myname}} password={{mypass}} priv=*.*:ALL host=localhost state=present
  
#- name: Install Mysql package
#  apt: name={{ item }} state=installed
#  with_items:
#   - mysql-server
#   - MySQL-python
#   - libselinux-python
#   - libsemanage-python

#- name: Configure SELinux to start mysql on any port
#  seboolean: name=mysql_connect_any state=true persistent=yes
#  when: sestatus.rc != 0

#- name: Create Mysql configuration file
#  template: src=my.cnf.j2 dest=/etc/my.cnf
#  notify:
#  - restart mysql

#- name: Start Mysql Service
#  service: name=mysqld state=started enabled=yes

#- name: insert iptables rule
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables

#- name: Create Application Database
#  mysql_db: name={{ dbname }} state=present

#- name: Create Application DB User
#  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
