---
# These tasks install http and the php modules.

#- name: Install http and php etc
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name = {{item}} state=present
  with_items :
    -libapache2-mod-php5

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes
  #apt: name={{ item }} state=present
  #with_items:
  # - apache2   #se cambia htp por apache2
  # - php
  # - php-mysql
   #- git
  # - libsemanage-python
   #- libselinux-python

#- name: insert iptables rule for httpd
#  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables

#- name: http service state
#  service: name=apache2 state=started enabled=yes

#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
#  when: sestatus.rc != 0
